version: "3.2"
services:
  php:
    build: 
      context: .
    image: amakundu/moe-php-mysql-demo:1.0.0
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=moe-mysql-app
      - MYSQL_USER=moeuser
      - MYSQL_PASSWORD=moepass
      - MYSQL_DB=moe_db
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:80"
    container_name: moe-php-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=moeuser
      - MYSQL_PASSWORD=moepass 
      - MYSQL_DATABASE=moe_db
    container_name: moe-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=moe-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: moe-phpmyadmin-app
networks:
  frontend:
  backend:
